version: '3'

services:
  api-solid-pg:
      image: bitnami/postgresql
      ports:
        - 5432:5432
      environment: 
        - POSTGRESQL_USERNAME=lockbox
        - POSTGRESQL_PASSWORD=lockbox
        - POSTGRESQL_DATABASE=dblockbox
